table Sales
	lineageTag: 26ec20c7-06d6-56ad-81f3-069dfb1636c5

	/// Net revenue after discounts.
	measure 'Total Sales' = SUM ( Sales[Revenue] )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Sales
		lineageTag: 240d8c85-cdb7-559d-b674-9c3bb9907d9c

	/// Cost of goods and services sold.
	measure 'Total Cost' = SUM ( Sales[Cost] )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Sales
		lineageTag: b94017b4-9b45-51f2-a157-5dc32c85952d

	/// Revenue less cost.
	measure 'Gross Profit' = [Total Sales] - [Total Cost]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Profitability
		lineageTag: f007f210-64b3-53fa-bb94-796309c1b3f9

	/// Gross profit as a share of revenue.
	measure 'Gross Margin %' = DIVIDE ( [Gross Profit], [Total Sales] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Profitability
		lineageTag: 58e2b1f6-20cf-5dc7-8214-ceaff5e3f964

	/// Number of distinct orders.
	measure 'Orders' = DISTINCTCOUNT ( Sales[Order ID] )
		formatString: #,0
		displayFolder: Sales
		lineageTag: c9c9f196-a209-567b-a4b4-4d05252383cc

	/// Units shipped.
	measure 'Units Sold' = SUM ( Sales[Units] )
		formatString: #,0
		displayFolder: Sales
		lineageTag: 401f30b5-aede-5f63-8127-3623815bba2b

	/// Revenue per order.
	measure 'Avg Order Value' = DIVIDE ( [Total Sales], [Orders] )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Sales
		lineageTag: 1d67f1ed-96f6-55d6-badf-683809c8e2cb

	/// Sales for the same dates one year earlier. The calendar stops at the last order date, so a part-year compares like for like.
	measure 'Sales PY' = CALCULATE ( [Total Sales], SAMEPERIODLASTYEAR ( 'Calendar'[Date] ) )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Growth
		lineageTag: 73db7dfe-9c4c-54f8-a22b-5a3927ecaae5

	/// Growth on the same period last year.
	measure 'Sales YoY %' = DIVIDE ( [Total Sales] - [Sales PY], [Sales PY] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Growth
		lineageTag: 9f02f5ba-7761-5830-84af-0843e82dedfe

	/// Monthly country targets, summed to the current filter. Targets are not set per
	/// channel or product, so the measure is blank when either is filtered rather than
	/// comparing part of the sales with the whole target.
	measure 'Sales Target' =
			IF (
			    NOT ISFILTERED ( Sales[Channel] ) && NOT ISFILTERED ( Products ),
			    SUM ( Targets[Target] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Target
		lineageTag: d1e654a0-a4b9-5887-918c-0c400e646734

	/// Sales above (+) or below (-) target.
	measure 'Variance to Target' = IF ( NOT ISBLANK ( [Sales Target] ), [Total Sales] - [Sales Target] )
		formatString: +\$#,0;-\$#,0;\$#,0
		displayFolder: Target
		lineageTag: 65fdfa55-3ccd-5804-bea7-c8dbb067cfea

	/// Sales as a share of target; 100% means on plan.
	measure 'Target Attainment %' = DIVIDE ( [Total Sales], [Sales Target] )
		formatString: 0.0%
		displayFolder: Target
		lineageTag: 58d3053f-780c-58a6-a208-47edb82c175d

	/// Share of the sales in view contributed by the current region or country.
	measure 'Region Share %' = DIVIDE ( [Total Sales], CALCULATE ( [Total Sales], ALLSELECTED ( Geography ) ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales
		lineageTag: 90ebb421-1aa3-5e4a-add7-c1a4a20d39ae


	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: 0afccfc6-a341-5ac8-a815-01367a731da2
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: b8c9ad3e-9d56-5016-9aff-e92a5116e342
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Country ID'
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: f53689d8-cd57-5740-944f-72b76ee756a1
		summarizeBy: none
		sourceColumn: country_id

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 6829c1d0-4ded-5722-832d-afe660138ec2
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: a83b10aa-dd79-5f4d-ab0e-72d24d962887
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: int64
		formatString: #,0
		lineageTag: 4edf62ef-0fac-5d42-a735-be70b839d400
		summarizeBy: sum
		sourceColumn: units

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		isHidden
		lineageTag: 46cd1261-bf59-557c-8a14-22ce69fffbaa
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		isHidden
		lineageTag: 469c67dd-b1ff-5933-9b52-687a236481cf
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
					Folder = if Text.EndsWith(DataFolder, "\") then DataFolder else DataFolder & "\",
					Source = Csv.Document(File.Contents(Folder & "sales.csv"), [Delimiter = ",", Columns = 8, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"order_id", Int64.Type}, {"order_date", type date}, {"country_id", Int64.Type}, {"product_id", Int64.Type}, {"channel", type text}, {"units", Int64.Type}, {"revenue", Currency.Type}, {"cost", Currency.Type}}, "en-US")
				in
					Typed
